### ISSUE TITLE
SennaJS Problem when using Primefaces: Datatable / ColumnToggler

### ISSUE THREAD

**Issue by tvhdev** [liferay/liferay-frontend-projects#886] opened 2022-03-20 18:40 UTC
**Preamble**
Neil told me to "circumvent" SennaJS for my menu-links, see https://issues.liferay.com/projects/FACES/issues/FACES-3656 as it seems to be a SennaJS Problem.

**Describe the defect**

In our portlet we're using Primefaces' datatable widget to display a simple list of records. The column toggler is configured so the user is able to customize the visibility of the columns. 
![column toggler fields1](https://user-images.githubusercontent.com/29280823/157732904-1c6b18fe-2e9e-4c74-9fe2-3a21262b8b0a.png)
After the user within the organizational site /group/companyname clicks on a simple link to return to the user's private page /group/guest, somehow the column toggler fields are shown in the top left corner.
![column toggler fields2](https://user-images.githubusercontent.com/29280823/157732908-d291d9fb-3e83-4e85-bace-c310aac03f8e.png)

**Reproducer**
Create a liferay private page /group/guest and an organizational site /group/companyname with one page. The organizational site's page contains the primefaces portlet. The Link "Zurück" in the organizational site redirects to the user's private page /group/guest

**Environment:**
 - PF Version: 11.0.0
 - PF Theme: Default
 - JSF + version: Mojarra 2.2.20
 - Affected browsers: All
 - Liferay 7.4-ga13

**To Reproduce**
1. Configure a liferay 7.4-ga13 environment
2. Create a Primefaces Portlet using the https://faces.liferay.dev/ toolbox
3. Create a liferay "private page" and an "organizational" site with one page and a "Zurück" Link
4. Insert the Primefaces Portlet into the organizational site's "first" page.
5. Klick on "Zurück"
6. See error

If you remove the column toggler, no problems occur at all. The column togglers code as follows

`      				    
...
<p:columnToggler datasource="schutzrechte" trigger="toggler">
		                    	<p:ajax event="toggle" listener="#{schutzrechteHelper.onColumnToggle}" update=":form:msgs"/>
		                    </p:columnToggler>		                    
...
`

**Expected behavior**
No residues of the column togglers entries are shown.

**Comment by izaera** [comment] 2022-06-16 07:51
Hi there:

Looking at the linked issue and the description here it looks like this is a case where Senna needs to be configured to avoid doing an XHR request so it wouldn't be a bug, maybe. I mean, as Neil says, Senna cannot cover any possible scenario out there and that's the reason why it provides attributes and flags to disable it for certain parts of the application.

In any case, if we want to continue with this issue, we need to know what's really happening and how to reproduce the problem with Senna alone. We don't have any idea on how Primefaces works or what it does, so we need to know exactly under which circumstances Senna is failing and why.

Then, we also need a proposed solution unless it is obvious after providing the failure in isolation.

Also, I would advise to consider reporting this through Liferay DXP support as the Portal contains a tweaked version of Senna so it may be very possible that this doesn't happen with vanilla Senna, or that a different thing occurs.

I'll leave this issue open in case you can provide this information. On the other hand, if you prefer to route it through support we may close it here.

Thanks :-)

**Comment by izaera** [comment] 2022-07-18 10:55
Closed due to inactivity. Feel free to reopen if needed.

**Closed by izaera** 2022-07-18 10:55 UTC
Labels: bug, senna, need-more-info
