### ISSUE TITLE
Investigate the testability of packages in DXP

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#630] opened 2021-08-27 16:28 UTC
Ideally we should have documented how to test each of our packages in DXP locally without having to cut a pre-release on npm. For this issue, we should document any missing cases and additionally we should investigate if we can make the testability easier in DXP. We

**Comment by izaera** [comment] 2021-09-29 06:44
I would like to remember the audience that there's a failsafe method: using a local npm registry. That makes testing possible for any possible combination of projects, and a unified and reproducible way to do it.

I agree the learning curve is somewhat steep, but it is worth the effort, IMO.

**Comment by izaera** [comment] 2021-09-30 06:07
> I sampled it a bit and still found it tricky and there were some hurdles with having to publish and version packages appropriately.

Yes, that's true. In fact I have some shell scripts on top of the solution to make it more user friendly and make sure I don't release to the public npm registry.

Maybe we can have a look at standardizing it and, at the same time, make all projects release versions with the same process (we began unifiying this but never finished it :-( ) and put any utility we need in that standard process. Ideally everything should use [js-publish](https://github.com/liferay/liferay-frontend-projects/tree/master/projects/npm-tools/packages/js-publish) to release. Maybe we can add support for the local releases there.

**Comment by bryceosterhaus** [comment] 2021-09-30 16:21
> Maybe we can have a look at standardizing it and, at the same time, make all projects release versions with the same process

This would be a great start, and it would likely make it easier to test with a local registry as well.

**Comment by izaera** [comment] 2021-10-04 06:22
I will try to apply the pattern to target-platforms (inspired by js-toolkit). Once we get it to work, it should be easy to move it to other projects as target-platforms is one of the most difficult projects to test, due to the complex graph of dependencies it generates.

**Comment by izaera** [comment] 2021-10-21 10:12
Since we already have a framework project for this abstract feature, I'm closing this issue and we shall create newer issues with feature requests for the framework project (local-npm).

**Closed as completed by izaera** 2021-10-21 10:12 UTC
Labels: docs, chore
