### ISSUE TITLE
Update to Webpack version to v5

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#224] opened 2020-11-05 11:40 UTC
Part of our strategy to [As a DXP Frontend Developer, I want a robust, efficient and straightforward way to bundle my applications](https://issues.liferay.com/browse/LPS-122162) is based on us using Webpack5 for our build process.

We already bundle Webpack as part of `@liferay/npm-scripts` so it can be used in DXP. We're currently use the following:

| package | dependency | DXP yarn.lock version |
| --- | ---| --- |
| uglifyjs-webpack-plugin | ^2.2.0 | ??? |
| webpack | ^4.39.1 | 4.42.0 |
| webpack-cli | ^3.3.6 | 3.3.6 |
| webpack-dev-server | ^3.7.2 | 3.7.2 |

The goal of this task would be to prepare `@liferay/npm-scripts` to offer webpack5 rather than webpack4 as an initial step to simplify the integration in DXP.

**Considerations**
- There are a bunch of modules using webpack one way or another in DXP, so in the integration step, it's expected that we'll need to udpate them
- We could start by manually using webpack5 in DXP if we prefer, but this feels like a cleaner path forward and I don't think our current usage is so complex that require a more surgical approach
- So far, we've managed to use the same version of `@liferay/npm-scripts` even in older branches. If webpack5 changes require updates in configuration, we need to either backport those all the way back or figure out some kind of branching mechanism similar to what was done to drop IE11 support.

**Comment by wincent** [comment] 2020-11-05 14:52
This is a duplicate of https://github.com/liferay/liferay-frontend-projects/issues/147 but is more detailed than that one, so I'll close that one.

**Comment by jbalsas** [comment] 2020-11-05 14:53
Thanks!! 😍

**Comment by wincent** [comment] 2020-11-05 14:54
Just copy-pasting the links from #147 over to here:

- https://webpack.js.org/blog/2020-10-10-webpack-5-release/
- https://webpack.js.org/migrate/5/

**Comment by izaera** [comment] 2022-04-12 10:21
We already have webpack 5 in npm-scripts.

**Closed by izaera** 2022-04-12 10:21 UTC
Labels: chore, npm-scripts, npm-tools
