### ISSUE TITLE
Missing dependency errors with React generated widgets.

### ISSUE THREAD

**Issue by 07Gond** [liferay/liferay-frontend-projects#631] opened 2021-08-27 16:35 UTC
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description

I spend last days dealing with Liferay with React projects but I have an issue around missing dependencies when I want to create a React widget.

**Desired behavior:**

Ability to use external npm modules in the project.

**Current behavior:**

**Repro instructions (if applicable):**
- If a create a **react widget** using **yeoman generator**, works well with the Hello World part but as soon as I added an additional dependency it crash with messages about **missing dependencies**.
- I recreated the same using **blade cli** with a fresh workspace, works well with the Hello World but, again, as soon as I added an additional dependency it crash with messages about **missing dependencies**.

Aditional data:
- If I adapt a React app to Liferay works "fine" but as I need some Liferay features as configuration we are not going to choose that road unless you tell me I can use configuration with react adapted widget.

**Other information (environment, versions etc):**
Liferay version: 7.2
Environment: Test on Local and deployed DXP.

**Comment by 07Gond** [comment] 2021-08-28 17:43
These type of errors:

![image](https://user-images.githubusercontent.com/2708687/131226276-6ba2e8d1-0b91-4046-aec2-91c284e7f237.png)
![image](https://user-images.githubusercontent.com/2708687/131226297-983ce21c-18b8-4c84-93e8-8feb26b69f8f.png)

But, as I said: Even if i try with only 1 dependency in one generated widget from scratch, it happens. With yeoman generator and with blade cli.

**Comment by bryceosterhaus** [comment] 2021-08-30 17:59
I just tried to reproduce locally and wasn't able to get your result. It worked fine for me.

My steps of reproducing:
1. `npm install -g generator-liferay-js`
2. `yo liferay-js` - Choose react project w/ sample code
3. `npm install --save react-bootstrap` (use any package here)
4. Add `react-bootstrap` code to app
5. `npm run build`
6. Deploy jar to dxp instance

**Comment by bryceosterhaus** [comment] 2021-08-30 18:00
If you can share your exact project or sample project you are using, that would help us narrow down what the issue might be.

**Comment by izaera** [comment] 2022-04-11 14:24
I'm closing since we didn't get any reply from OP.

**Closed by izaera** 2022-04-11 14:24 UTC
Labels: js-toolkit, need-more-info
