### ISSUE TITLE
yo Liferay-JS fails to compile on start

### ISSUE THREAD

**Issue by natemking** [liferay/liferay-frontend-projects#592] opened 2021-06-16 14:01 UTC
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x ] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :two: v2.x
-   [ ] :three: v3.x

### Description
After running the JS generator to create a React app , `npm run start` errors out with a 'Failed to compile' error. Due to this the Bundle generator is the workaroud despite the warning message when creating w/ the Bundle gen that states to start using the JS gen exclusively. 

**Desired behavior:**
The app launches in localhost:8081.

**Current behavior:**
Error output: 
```
test ➤ npm run start                                                                          

> test@1.0.0 start /home/natemking/liferay/test
> lnbs-start

ℹ ｢wds｣: Project is running at http://localhost:8081/

ℹ ｢wds｣: webpack output is served from /o/test/

✖ ｢wdm｣: Hash: 46f04de298a55fe384c1
Version: webpack 4.29.6
Time: 453ms
Built at: 06/16/2021 9:44:43 AM
                Asset       Size  Chunks             Chunk Names
         .placeholder    0 bytes          [emitted]  
       css/styles.css  139 bytes          [emitted]  
    webpack.bundle.js    341 KiB    main  [emitted]  main
webpack.bundle.js.map    392 KiB    main  [emitted]  main
Entrypoint main = webpack.bundle.js webpack.bundle.js.map
[0] multi ../node_modules/webpack-dev-server/client?http://localhost:8081 ./index.js 40 bytes {main} [built]
[../node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[../node_modules/ansi-regex/index.js] 135 bytes {main} [built]
[../node_modules/events/events.js] 14.5 KiB {main} [built]
[../node_modules/html-entities/lib/index.js] 449 bytes {main} [built]
[../node_modules/loglevel/lib/loglevel.js] 8.65 KiB {main} [built]
[../node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[../node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[../node_modules/url/url.js] 22.8 KiB {main} [built]
[../node_modules/webpack-dev-server/client/index.js?http://localhost:8081] ../node_modules/webpack-dev-server/client?http://localhost:8081 8.1 KiB {main} [built]
[../node_modules/webpack-dev-server/client/overlay.js] 3.59 KiB {main} [built]
[../node_modules/webpack-dev-server/client/socket.js] 1.05 KiB {main} [built]
[../node_modules/webpack/hot sync ^\.\/log$] ../node_modules/webpack/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[../node_modules/webpack/hot/emitter.js] 75 bytes {main} [built]
[./index.js] 417 bytes {main} [built]
    + 12 hidden modules

ERROR in ./index.js
Module not found: Error: Can't resolve 'babel-loader' in '/home/natemking/liferay/test/.webpack'
 @ ./index.js 14:11-37
 @ multi ../node_modules/webpack-dev-server/client?http://localhost:8081 ./index.js

ℹ ｢wdm｣: Failed to compile.

⚠ ｢wds｣: Unable to open browser. If you are running in a headless environment, please do not use the --open flag

ℹ ｢wdm｣: Compiling...

✖ ｢wdm｣: Hash: 46f04de298a55fe384c1
Version: webpack 4.29.6
Time: 47ms
Built at: 06/16/2021 9:44:43 AM
 2 assets
Entrypoint main = webpack.bundle.js webpack.bundle.js.map
[./index.js] 417 bytes {main} [built]
    + 26 hidden modules

ERROR in ./index.js
Module not found: Error: Can't resolve 'babel-loader' in '/home/natemking/liferay/test/.webpack'
 @ ./index.js 14:11-37
 @ multi ../node_modules/webpack-dev-server/client?http://localhost:8081 ./index.js

ℹ ｢wdm｣: Failed to compile.

```

Installing Babel loader as per the error message does not resolve the issue. 

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**
generator-liferay-js@2.26.0

**Comment by izaera** [comment] 2021-06-17 07:35
:thinking: We will have a look at this. However, a failing `npm run start` does not prevent development because it is an auxiliary feature. So, as long as you can `build` and `deploy` to Liferay Portal without failure, you should be able to continue development.

Another workaround may be using `npm run start eject` (see [this commit](https://github.com/liferay/liferay-frontend-projects/commit/e81754b63cec534d78bd830d4ad2a56a9d7e0e3f#diff-8695ffb5c049886c23fc22abfe8affc523c3cbde785073acc2129710960366db) for more information on how to use it and what it does) and workaround the failure by hand while it's being fixed.

**Comment by kresimir-coko** [comment] 2021-07-23 08:03
I can confirm that I get the above error log when running `npm run start` on a fresh React project.

**Comment by vincentvandyck** [comment] 2021-08-12 07:40
Hello,
I've also ran into this issue when starting from a newly generated project. I looked into it a bit and getting passed the _babel-loader_ dependency can be done by manually installing it, but then I ran into an issue with the babel-react preset not being found, even though it is installed locally. 

Is there any progress on this already as the issue has been assigned? 

(Also want to mention that building/deploying the application works without fault. So this would just be to improve the local development experience afaik.)

**Comment by izaera** [comment] 2021-08-16 07:17
Hi @vincentvandyck 

We investigated the issue and came to the conclusion that it was in fact an issue and it was related to the the generator not listing all needed dependencies on first place.

However, once we fixed that, another error appeared and didn't investigate any more. So this is not currently under development until we find some time to address it.

**Comment by kresimir-coko** [comment] 2022-05-06 09:55
Hey @izaera should we leave this open or close it and address it later. Basically, is it possible we forget about the "another error" you mentioned. If its easy to forget about, then we might wanna keep this up.

**Comment by izaera** [comment] 2022-05-09 07:15
I would say we can close it, because we have moved all this stuff to the new @liferay/cli and the codebase has been modified so it's very possible that this doesn't happen any more.

**Closed by izaera** 2022-05-09 07:15 UTC
Labels: bug, js-toolkit, 2.x
