### ISSUE TITLE
Angular 8 with nebular and ngx-bootstrap not displaying and errors shown in browser console

### ISSUE THREAD

**Issue by LidoDev** [liferay/liferay-frontend-projects#190] opened 2020-09-25 23:06 UTC
I have a project angular 8 based on ngx-admin template and nebular 4.6.0 and scss styles sheet. The adapt, build and deploy scripts works correctly. But when i want to add the portlet from the backoffice of liferay i get this error on console:

liferay-amd-loader | Errors returned from server for require( ["portlet-paiement@0.0.0"] ): 
(3) ["Missing dependency 'portlet-paiement@0.0.0/portlet…ement/main-es5' of 'portlet-paiement@0.0.0/index'", "Missing dependency 'portlet-paiement@0.0.0/portlet…/polyfills-es5' of 'portlet-paiement@0.0.0/index'", "Missing dependency 'portlet-paiement@0.0.0/portlet…nt/runtime-es5' of 'portlet-paiement@0.0.0/index'"]
0: "Missing dependency 'portlet-paiement@0.0.0/portlet-paiement/main-es5' of 'portlet-paiement@0.0.0/index'"
1: "Missing dependency 'portlet-paiement@0.0.0/portlet-paiement/polyfills-es5' of 'portlet-paiement@0.0.0/index'"
2: "Missing dependency 'portlet-paiement@0.0.0/portlet-paiement/runtime-es5' of 'portlet-paiement@0.0.0/index'"

and the second error in the same stack is :

liferay-amd-loader | 
 A require() call has failed but no failure handler was provided.
 Note that even if the call stack of this error trace looks like coming from the Liferay AMD Loader, it is not an error in the Loader what has caused it, but an error caused by the require() call.
 The reason why the Loader is in the stack trace is because it is printing the error so that it doesn't get lost.
 However, we recommend providing a failure handler in all require() calls to be able to recover from errors better and to avoid the appearance of this message.
 
 Some information about the require() call follows:
   · Require call id: 120 
   · Required modules: ["portlet-paiement@0.0.0"] 
   · Missing modules: (n/a) 
   · Stack trace of the require() call: 
        Error
            at e.value (http://localhost:8080/combo?browserId=chrome&minifierType=js&languageId=en_US&b=7304&t=1601071485105&/o/frontend-js-aui-web/aui/widget-stdmod/widget-stdmod.js&/o/frontend-js-aui-web/aui/aui-aria/aui-aria.js&/o/frontend-js-aui-web/aui/aui-io-plugin-deprecated/aui-io-plugin-deprecated.js&/o/frontend-js-aui-web/aui/aui-io-request/aui-io-request.js&/o/frontend-js-aui-web/aui/aui-loading-mask-deprecated/aui-loading-mask-deprecated.js&/o/frontend-js-aui-web/aui/aui-overlay-base-deprecated/aui-overlay-base-deprecated.js&/o/frontend-js-aui-web/aui/aui-overlay-context-deprecated/aui-overlay-context-deprecated.js&/o/frontend-js-aui-web/aui/aui-overlay-manager-deprecated/aui-overlay-manager-deprecated.js&/o/frontend-js-aui-web/aui/aui-overlay-mask-deprecated/aui-overlay-mask-deprecated.js&/o/frontend-js-aui-web/aui/aui-parse-content/aui-parse-content.js&/o/frontend-js-aui-web/liferay/session.js&/o/frontend-js-aui-web/liferay/deprecated.js&/o/frontend-js-web/loader/config.js&/o/frontend-js-web/loader/loader.js&/o/frontend-js-web/misc/svg4everybody.js&/o/frontend-js-web/liferay/dom_task_runner.js&/o/frontend-js-web/liferay/events.js&/o/frontend-js-web/liferay/lazy_load.js&/o/frontend-js-web/liferay/liferay.js&/o/frontend-js-web/liferay/global.bundle.js&/o/frontend-js-web/liferay/portlet.js&/o/frontend-js-web/liferay/workflow.js:140:259)
            at <anonymous>:2:17
            at runNextScript (http://localhost:8080/combo/?browserId=chrome&minifierType=&languageId=en_US&b=7304&t=1601071485105&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/components/CollectionItemContext.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/config/constants/itemActivationOrigins.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/config/constants/itemTypes.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/components/Controls.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/services/CollectionService.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/common/components/RawDOM.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/components/UnsafeHTML.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/components/layout-data-items/Collection.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/utils/useDragAndDrop.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/components/CollectionActiveItemContext.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/components/DragPreview.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/core/debounceRAF.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/config/constants/viewportSizes.js&/o/js/resolved-module/@frontend-taglib-clay$clayui/popover@3.4.3/lib/index.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/components/GlobalContext.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/app/components/DisabledArea.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/prop-types/ConfigurationFieldPropTypes.js&/o/js/resolved-module/layout-content-page-editor-web@2.0.46/page_editor/prop-types/BackgroundImagePropTypes.js:54:30) 
 Error: The server generated some errors while resolving modules
    at combo?browserId=chrome&minifierType=js&languageId=en_US&b=7304&t=1601071485105&/o/frontend-js-aui-web/aui/widget-stdmod/widget-stdmod.js&/o/frontend-js-aui-web/aui/aui-aria/aui-aria.js&/o/frontend-js-aui-web/aui/aui-io-plugin-deprecated/aui-io-plugin-deprecated.js&/o/frontend-js-aui-web/aui/aui-io-request/aui-io-request.js&/o/frontend-js-aui-web/aui/aui-loading-mask-deprecated/aui-loading-mask-deprecated.js&/o/frontend-js-aui-web/aui/aui-overlay-base-deprecated/aui-overlay-base-deprecated.js&/o/frontend-js-aui-web/aui/aui-overlay-context-deprecated/aui-overlay-context-deprecated.js&/o/frontend-js-aui-web/aui/aui-overlay-manager-deprecated/aui-overlay-manager-deprecated.js&/o/frontend-js-aui-web/aui/aui-overlay-mask-deprecated/aui-overlay-mask-deprecated.js&/o/frontend-js-aui-web/aui/aui-parse-content/aui-parse-content.js&/o/frontend-js-aui-web/liferay/session.js&/o/frontend-js-aui-web/liferay/deprecated.js&/o/frontend-js-web/loader/config.js&/o/frontend-js-web/loader/loader.js&/o/frontend-js-web/misc/svg4everybody.js&/o/frontend-js-web/liferay/dom_task_runner.js&/o/frontend-js-web/liferay/events.js&/o/frontend-js-web/liferay/lazy_load.js&/o/frontend-js-web/liferay/liferay.js&/o/frontend-js-web/liferay/global.bundle.js&/o/frontend-js-web/liferay/portlet.js&/o/frontend-js-web/liferay/workflow.js:143

**Comment by izaera** [comment] 2021-04-16 10:25
This seems like a duplicate of the above #191, due to an unsupported Angular version. We have upgraded that support in the last months so this is probably obsolete by now.

I'm closing the issue. Feel free to reopen if it still doesn't work for you, following [these steps](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) first to obtain more accurate information.

**Closed by izaera** 2021-04-16 10:25 UTC
Labels: 2.x, js-toolkit
