### ISSUE TITLE
Liferay packages not loading from @liferay/cli generated remote app when using live development

### ISSUE THREAD

**Issue by nitramek** [liferay/liferay-frontend-projects#1048] opened 2022-11-23 08:44 UTC
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :two: v2.x
-   [x] :three: v3.x

### Description

**Desired behavior:**
Deployed/Live session remote app generated via  `liferay@cli` shows correctly.

**Current behavior:**
Generated project using `liferay@cli`, choosing Portal 7.4 and Remote App with React.
When using `liferay start` the remote app is deployed but can't load external scripts (for example `react.js`). It tries to load them from the webpack server (`localhost:8081/o/frontend-js-react-web/__liferay__/exports/react.js`) where it looks like they dont exist instead of Liferay (`localhost:8080/o/frontend-js-react-web/__liferay__/exports/react.js`). Thanks to these remote app doesnt show at all.

My workaround for now is to use absolute url in `liferay.json` such as `http://localhost:8080/o/frontend-js-react-web/__liferay__/exports/react.js` instead of provided `/o/frontend-js-react-web/__liferay__/exports/react.js`. 

**Repro instructions (if applicable):**
1. Generate project using `liferay new`, targeting Portal 7.4, Remote App with React.
2. Run `liferay start`
3. Add remote widget to page
4. Remote widget does not show at all
**Other information (environment, versions etc):**
Portal 7.4 49GA
Node 16.18.0

**Comment by izaera** [comment] 2022-11-24 07:26
[NOTE: this bug is being tracked internally at https://issues.liferay.com/browse/LPS-169496]

**Comment by izaera** [comment] 2023-01-09 09:26
I have created a project with the latest version of `@liferay/cli` and it works seamlessly for me:

![image](https://user-images.githubusercontent.com/3273630/211276019-35918da8-ba54-4f1f-bd7d-c030795a1130.png)

See in the attached screenshot how `npm run start` starts and correctly reports that it will be fetching `react` and `react-dom` from Liferay Portal.

Also, see in Firefox (inside the screenshot) how the path to the .js files in the top import statements is correctly pointing to `/o/frontend-js-react-web/__liferay__/exports/....`, which is the path where those .js files live inside Liferay Portal.

**Comment by izaera** [comment] 2023-01-09 09:31
Can you please follow the same steps to see how the built `index.js` looks like in your case?

You just need to execute `npm run start`, then open `http://localhost:8081/index.js` in a browser. That will show how `@liferay/cli` (and webpack) is generating that file and how the imports from `react` and `react-dom` look like.

Alternatively, you can run `npm run build` and see how the generated zip file looks like (though I'm afraid you will be affected by https://github.com/liferay/liferay-frontend-projects/issues/1049 :-/ ).

**Comment by nitramek** [comment] 2023-01-09 09:35
I can check whenever I will have a moment. Should be today.

But I remember the problem wasn't about the js file itself. It was when I placed the remote app widget into liferay page. It tried to load from the `/o/frontend-js-react-web` from `http://localhost:8081/` not from the liferay which resides in `localhost:8080` by default. And it didnt load from the webpack server.

**Comment by izaera** [comment] 2023-01-09 10:23
Yes, but that's very strange, because if you look at the screenshot, the generated `index.js` imports `react` from `/o/frontend-js-react-web/...` without anchoring it to any host or port.

Thus, when you include that `index.js` file inside Liferay Portal and fetch it from, say, `http://localhost:8080`, the unanchored `import` must be fetched from the page base URL (`http://localhost:8080`) not from `http://localhost:8081`, as it is not the address you are using in the browser address bar.

**Comment by izaera** [comment] 2023-01-09 10:25
In other words, `import` URLs are relative to the page (address bar URL), not to the URL from where the script was fetched. So there's no way the browser can use `http://localhost:8081` instead of `http://localhost:8080`, unless:

1. It is specifically specified in the .js file 
2. You are fetching a proxied Liferay Portal from `http://localhost:8081`

**Comment by nitramek** [comment] 2023-01-09 11:47
Allright, I tried newly generated project on Windows with `liferay new`.

Target platform: Liferay Portal CE 7.4
Shadow dom: No

`npm install`, then `npm run start` with the same versions reported on top.

Then I removed all rules from `styles.css` to work around the bug.

After that I dragged the remote widget to home page and it just tries to load from `localhost:8081` 

This is `localhost:8081/index.js`
![index.js](https://user-images.githubusercontent.com/5571015/211299699-5610966c-8359-411e-8ab0-e108f00fc2d1.png)
Some more info
![image](https://user-images.githubusercontent.com/5571015/211300684-7cd262cc-db86-4868-839d-54e778e359c5.png)

In terminal everything is green webpack compiled successfully.

**Comment by izaera** [comment] 2023-01-09 12:41
I've downloaded your version of Liferay Portal and I'm able to reproduce it too :+1: .

**Comment by izaera** [comment] 2023-01-09 12:47
Which makes me think this statement is wrong:

> In other words, import URLs are relative to the page (address bar URL), not to the URL from where the script was fetched. So there's no way the browser can use http://localhost:8081 instead of http://localhost:8080

But how has it worked until now, then? :thinking:

**Comment by izaera** [comment] 2023-01-09 12:50
From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules):

> You use the [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) statement, followed by a comma-separated list of the features you want to import wrapped in curly braces, followed by the keyword from, followed by the module specifier.

> The module specifier provides a string that the JavaScript environment can resolve to a path to the module file. In a browser, this could be a path relative to the site root, which for our basic-modules example would be /js-examples/module-examples/basic-modules. However, here we are instead using the dot (.) syntax to mean "the current location", followed by the relative path to the file we are trying to find. This is much better than writing out the entire absolute path each time, as relative paths are shorter and make the URL portable — the example will still work if you move it to a different location in the site hierarchy.

Which is ambiguous, because "site root" can be the page's site root or the .js module site root when two servers are involved.

**Comment by izaera** [comment] 2023-01-09 14:44
I can make it fail with master too (in Linux). I suppose this has never worked, then :shrug: 

However, I would have sworn that I saw this working before. Maybe we've been deploying projects using the _agnostic_ platform only.

Or maybe we haven't tested this feature since we [stopped using import maps](https://issues.liferay.com/browse/LPS-164784).

**Comment by izaera** [comment] 2023-01-09 14:46
The problem with this is that it not only affects `npm run start`, but in theory, also any remote app wishing to consume `react` from Portal and being served from an external server.

**Comment by nitramek** [comment] 2023-01-09 15:21
Interesting - that is true they would need to provide absolute URLs as a workaround.

**Comment by izaera** [comment] 2023-01-10 07:54
So, after reflecting about this a bit, I think the only possible solutions to this are:

1. Use import maps (but we can't because [some browsers still don't support them](https://caniuse.com/?search=import%20maps) and the shim produces double executions of some modules due to the way it works).
2. Specify the base URL of external imports at build time

The best solution would be number 1, because sometimes it is not possible to know where different things will be deployed at runtime and import maps lets us wire things together at deploy (or even run) time.

The thing is that, in a distributed setup, you may want to import external modules not only from portal, but also from other hosts. Imagine, for example, that you have three servers:

1. myportal.com
2. mycustomelements.com
3. mysharedlibs.com

And you want to host custom elements at number 2, and some utility libraries at number 3, then use `react` from the Portal. In this scenario, there's no way to make this work without either import maps, or hardcoding the server URLs at build time in the produced artifacts so that the browser knows where to get the libs, custom elements, and `react` from.

**Comment by izaera** [comment] 2023-01-10 14:04
After some internal brainstorming, for now we think this is only a problem with `npm run start` and not a problem with real production deployments as explained in my two previous comments. 

This is because 99% of the production setups will be using a unique domain name for the host (whether or not they use a CDN) since otherwise, they will need to take care of CORS, https certs, and make sure to wire things properly which, AFAIK, apart from webpack federated builds, nobody is doing on a regular basis, because there are no tools aimed at that.

If, in the future, we think that a multihost setup makes sense, we can either tell users to tweak their liferay.json files or implement some feature in @liferay/cli to make those setups easier.

----

As to the `npm run start` feature, we will probably need to ask for the URL of the local Liferay installation (in addition to the deployment directory) and either:

1. Make a specific build for live development that prepends that URL to the external imports
2. Proxy the Portal through webpack dev server so that everything comes from the same host (that would be `localhost:8081` instead of a mix of `localhost:8080` and `localhost:8081`).

Solution 2 may be better because it would also prevent any possible CORS issue that could arise because of using two different hosts in the same page.

**Comment by izaera** [comment] 2023-01-17 15:06
This may be fixed once we find out how to share code between client extensions, which is being investigated at https://issues.liferay.com/browse/LPS-169939

**Comment by izaera** [comment] 2023-10-06 06:54
I can confirm that this was fixed when we implemented https://issues.liferay.com/browse/LPS-169939

**Closed by izaera** 2023-10-06 06:54 UTC
Labels: bug, js-toolkit, 3.x
