### ISSUE TITLE
Expand portlet configuration dialog capabilities

### ISSUE THREAD

**Issue by jwanner83** [liferay/liferay-frontend-projects#187] opened 2020-10-16 07:39 UTC
Hey there! We currently have a highly customizable portlet and we would like to migrate and refactore it to a new, JavaScript only Portlet without the need for JSP and Java. The only thing that prevents us to do so are the limited options in the configuration feature.

1. Missing translatable fields
One of our configuration is responsible to define the content of a confirmation mail. This content needs to be translatable.
![image](https://user-images.githubusercontent.com/38656104/93333243-5281bf00-f823-11ea-954d-4165a9ac560d.png)

2. Missing repeatable fields
Another configuration contains some ids which are currently repeatable. It would be very cool to just add a key to the configuration to define that this field is repeatable.
![Bildschirmfoto 2020-09-16 um 14 04 26](https://user-images.githubusercontent.com/38656104/93334642-8c53c500-f825-11ea-837a-2cfe4ea3f57d.png)

3. Missing possibility to group configurations into tabs or something similar
Because our Portlet has so many configurations, we grouped them into 5 different tabs. This improves the overview a lot.
![image](https://user-images.githubusercontent.com/38656104/93334958-0421ef80-f826-11ea-9af8-22fbe719f9f1.png)

I would really like to hear your opinion to this topic.

(Btw. this Issue replaces the issue liferay/liferay-js-toolkit#623 because I noticed there are some more things missing, than only the translation feature of fields)

**Comment by Spydr331** [comment] 2021-04-09 19:47
I would also like to add that I added quite a bit of customization to the markup of the portlet configurations in my previous portlets and while researching how to move to angular using the liferay-js toolkit, I was disappointed by the lack of admin configuration control. For one example I had a table of checkboxes in order to organize them better for the user.

**Comment by izaera** [comment] 2021-05-12 13:56
This seems a duplicate of #195

**Closed by izaera** 2021-05-12 13:56 UTC
Labels: 2.x, duplicate, feat, js-toolkit
